apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 13.2.5
      helm:
        releaseName: grafana
        valueFiles:
          - $values/monitoring/grafana-values.yaml
    - repoURL: https://github.com/KoushikPraneeth/typescale-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
