apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.20.2
      helm:
        releaseName: keda
        valueFiles:
          - $values/monitoring/keda-values.yaml
    - repoURL: https://github.com/KoushikPraneeth/typescale-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
