apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typescale.appFullname" . }}
  labels:
    {{- include "typescale.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "typescale.appSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.app.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.app.metrics.path | quote }}
        prometheus.io/port: {{ .Values.app.metrics.port | quote }}
      {{- end }}
      labels:
        {{- include "typescale.appSelectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: typescale
          image: "{{ .Values.app.image.repository }}{{ if .Values.app.image.digest }}@{{ .Values.app.image.digest }}{{ else }}:{{ .Values.app.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            {{- if .Values.app.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.app.metrics.port }}
              protocol: TCP
            {{- end }}
          env:
            - name: REDIS_URL
              value: "redis://{{ include "typescale.redisFullname" . }}:{{ .Values.redis.service.port }}/0"
            - name: TYPESCALE_NAMESPACE
              value: {{ default (printf "typescale:%s" .Release.Namespace) .Values.app.namespacePrefix | quote }}
            {{- if .Values.app.metrics.enabled }}
            - name: METRICS_PORT
              value: {{ .Values.app.metrics.port | quote }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /health/startup
              port: http
            periodSeconds: {{ .Values.app.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.app.startupProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.app.containerSecurityContext | nindent 12 }}
