apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typescale.redisFullname" . }}
  labels:
    {{- include "typescale.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "typescale.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "typescale.redisSelectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}{{ if .Values.redis.image.digest }}@{{ .Values.redis.image.digest }}{{ else }}:{{ .Values.redis.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            - --save
            - ""
            - --appendonly
            - "no"
            - --port
            - {{ .Values.redis.service.port | quote }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - {{ .Values.redis.service.port | quote }}
                - ping
            initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - {{ .Values.redis.service.port | quote }}
                - ping
            initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.redis.containerSecurityContext | nindent 12 }}
