app:
  replicaCount: 2
  image:
    repository: ghcr.io/koushikpraneeth/typescale
    tag: 5abe5957d695932119da75bb2617a1d89965a54a
    digest: sha256:9048dceab6f278aa7098ba9239fcb8a80e26bc8423fdccc8f69e8876e4df2533
    pullPolicy: IfNotPresent
  namespacePrefix: typescale:gitops
  metrics:
    enabled: true
    path: /metrics
    port: 9090
    allowedNamespace: monitoring
  autoscaling:
    enabled: true
    minReplicaCount: 2
    maxReplicaCount: 5
    pollingInterval: 15
    cooldownPeriod: 300
    fallback:
      failureThreshold: 3
      replicas: 5
      behavior: static
    prometheus:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      jobName: typescale-pods
      query: ""
      threshold: "8"
      activationThreshold: "1"
  publicService:
    enabled: true
    type: LoadBalancer
    port: 80
