app:
  replicaCount: 2
  image:
    repository: ghcr.io/koushikpraneeth/typescale
    tag: 23e3f35c83c41b4aca7f4462082a3df9b0b4f812
    digest: sha256:9665cd5a4e1e972e3bdf812658487e893253f848c2047983084979cf8119ed47
    pullPolicy: IfNotPresent
  namespacePrefix: typescale:gitops
  publicService:
    enabled: true
    type: LoadBalancer
    port: 80
